### ISSUE TITLE
This Library's Cryptography is NOT Secure

### ISSUE THREAD

**Issue by sarciszewski** [all-ride/ride-lib-encryption#1]
https://github.com/all-ride/ride-lib-encryption/blob/3ff0061666e6e1e86f4f249a70ec8fb221ceb816/src/ride/library/encryption/cipher/GenericCipher.php

``` php
mcrypt_encrypt(
    MCRYPT_RIJNDAEL_256,
    $key,
    $data,
    MCRYPT_MODE_ECB,
    mcrypt_create_iv(
        mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_ECB),
        MCRYPT_RAND
    )
);
```
1. This encryption is not authenticated. To see why this is dangerous, please refer to [this blog post on encryption and authentication](https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly).
2. `MCRYPT_RIJNDAEL_256` is not a well-studied cipher. It's also not AES-256! `MCRYPT_RIJNDAEL_128` is the only mcrypt constant that works for AES. 
3. `MCRYPT_MODE_ECB` is [the worst mode to use for encryption](http://cryptopals.com/sets/2/challenges/12/).
4. `MCRYPT_RAND` gives predictable output, but this doesn't matter because ECB mode discards IVs.

**Comment by ride-user** [comment]
Thanks for pointing this out!

I've added an update with these points covered.
